name: clothes
description: Your online garderobe
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.2.0
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.17.0
  json_annotation: ^4.0.1
  mocktail: ^0.1.4
  path_provider: ^2.0.2

dev_dependencies:
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.3
  lint: ^1.5.3

flutter:
  generate: true
  uses-material-design: true
