name: clothes
description: Your online garderobe
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.2.0
  cached_network_image: ^3.0.0
  clock: ^1.1.0
  crop_your_image:
    git:
      url: https://github.com/danielgorka/crop_your_image
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  file: ^6.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  get_it: ^7.1.3
  hive: ^2.0.4
  image_picker: ^0.8.0+3
  injectable: ^1.4.1
  intl: ^0.17.0
  json_annotation: ^4.0.1
  mocktail: ^0.1.4
  path: ^1.8.0
  path_provider: ^2.0.2
  rxdart: ^0.27.1
  shimmer: ^2.0.0

dev_dependencies:
  auto_route_generator: ^2.1.0
  bloc_test: ^8.0.2
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.3
  lint: ^1.5.3

flutter:
  generate: true
  uses-material-design: true
